version: '3.0'
services:
  db:
    image: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-nutria}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE-nutria}'
      MYSQL_USER: '${DB_USERNAME-nutria}'
      MYSQL_PASSWORD: '${DB_PASSWORD-nutria}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - nutria
networks:
  nutria: